# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "35367a71c431749ad1fa3d7f1bd04e94"
name = "bin-location-extension"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobject_definitions, write_metaobject_definitions, read_metaobjects, write_metaobjects, read_products, write_products, read_inventory, write_inventory, read_users"

[auth]
redirect_urls = [
  "https://shopify.dev/apps/default-app-home/api/auth",
  "http://localhost:3000/api/auth/shopify/callback",
  "https://ezoko-frontend-test.up.railway.app/api/auth/shopify/callback"
]
